name: Java CI com Maven

# Gatilhos: roda em pushes para a branch main e em pull requests para a branch main
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # A máquina virtual que o job vai rodar
    runs-on: ubuntu-latest

    steps:
      # 1. Faz o checkout do código para a VM
      - name: Checkout do código
        uses: actions/checkout@v4

      # 2. Configura o JDK 11
      - name: Configurar JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      # 3. Executa o comando de teste do Maven
      - name: Executar testes com Maven
        run: mvn -B test